### PR TITLE
Implement binary exec / RPC based plugins for Machine

### PR DESCRIPTION
**Pull request by nathanleclaire**
# Docker Machine Driver Plugins
## Motivation

Many folks have expressed interest in writing or maintaining a driver for Machine but @ehazlett and I are incapable of reviewing and maintaining all of them ourselves.  Additionally, we are a bottleneck for when people want to add features and release new versions of existing drivers.  Therefore, we are moving to a plugin-based architecture.
## Usage

From the end user's perspective, the Machine CLI will be pretty similar to how it always has, with the additional caveat that binaries for the desired plugins must be installed as well as the core `docker-machine` binary.

For the plugin developer and/or distributor, there are some considerations to keep in mind.  All plugins must be Go binaries located in the end user's `PATH` with the name of `docker-machine-drivername`.  Once present, they will be usable.  

To implement a plugin, the driver developer must make a new repository with the plugin code, which:
- includes a properly named module (e.g. `virtualbox`) which contains a `struct` that fulfills the `Driver` interface from `github.com/docker/machine/libmachine/drivers`
- includes a `main` module (I've chosen to make this in a directory called `bin` in the `virtualbox` example presented here for this) which calls `plugin.RegisterPlugin()` with an instantiated instance of the struct.

Example from VirtualBox:

``` go
package main

import (
        "github.com/docker/machine/drivers/virtualbox"
        "github.com/docker/machine/libmachine/drivers/plugin"
)

func main() {
        plugin.RegisterDriver(new(virtualbox.Driver))
}
```
## Migrating an Existing Driver to a Plugin

This is for the time of writing and is likely to change, but I think through documenting things we can hopefully the most mundane details of this process through a script.

The most important / likely to trip up migrators details are:
- A lot of paths have changed, usually because the modules have been moved inside of `libmachine`.  Some examples:
  - `github.com/docker/machine/log` => `github.com/docker/machine/libmachine/log`
  - `github.com/docker/machine/utils` => `github.com/docker/machine/libmachine/mcnutils`
  - `github.com/docker/machine/drivers` => `github.com/docker/machine/libmachine/drivers`
- The `StorePath` expected by many drivers has been replaced by `GlobalArtifactPath` and `LocalArtifactPath` methods (formerly `ResolveStorePath`), but in the light of day I'm not really sold on this decision of mine, and may well change it back to the way it was before).
- The usage of `cli.Flag` in the drivers has changed to a Machine-specific model which is more RPC-friendly.  Essentially:
  - `GetCreateFlags` is now a required method on the `Driver` itself, not a module-level function, which returns `[]mcnflag.Flag` (a custom type encompassing all types of flags).  All instances of `cli.Flag` and/or concrete types that implement it should be replaced by `mcnflag.Flag`.
- It is no longer necessary to have the `init` block calling `Register` in the driver module
- It is conventional to have a `NewDriver` "factory" method in the driver module, but not actually required.
## Under The Hood

The way that plugins work is heavily inspired by Hashicorp's [Terraform](https://github.com/hashicorp/terraform).

When a Machine command is invoked, the following happens:
1. `Host` struct(s) is loaded up from disk, and instead of loading the literal driver struct like in the past, a `RpcClientDriver` is loaded into the `Driver` field.  This struct fulfills the Driver interface but is agnostic about the provider, it simply proxies methods to the RPC Driver server listening in the plugin binary.
2. An RPC plugin server (registered using the wrapper method detailed above) is spun up listening on an available TCP port on `localhost`, and the created RPC client connects to it.
3. Using the RPC client the configuration for the actual driver (running in the plugin binary) is set remotely.
4. When calls to the driver are made in the Machine code, they are sent over the wire to get a response from the plugin server.
5. When the host is saved to disk again, first it is ensured that the `RawDriver` is set as `[]byte` to ensure that the configuration can be set over the network again on subsequent invocations.
## Tooling

We don't have any tooling / default Machine plugin repository yet, but there are several things I'd like to see:
1. A base / example project at somewhere like https://github.com/docker/docker-machine-example which is easily forkable and has an example driver
2. A Makefile and some basic automation around compiling your driver and releasing the binaries to Github.
3. Detailed documentation explaining how to develop a driver and what the expectations are for each driver.  For instance, we need to be explicit that ports should be open and available for `22`, `2376`, `3376` in the case of Swarm master, etc.
## Caveat Emptor

Some of the underlying API / mechanics are likely to change, such as `libmachine` details.  Ultimately, however, it is our goal to make migrating existing work that has been done on drivers to the plugin-based model as smooth as possible.  To that end, we really want to get people playing with this ASAP, so feel free to reach out, comment, and attempt some implementations.
- N

### CODE REVIEW

**Comment by thaJeztah** [comment]
Good to see progress :+1: ; lots of todo's as well I see :smile:

**Comment by nathanleclaire** [comment]
Added some details.

**Comment by nathanleclaire** [comment]
Example plugin here: https://github.com/nathanleclaire/docker-machine-xhyve

@zchee @timfallmk Check it out!  I can help you to compile if you need.  I have gotten a create to run about halfway through with the driver but looks like the driver has an issue getting the DHCP lease on my computer.

**Comment by nathanleclaire** [comment]
You can see what I changed in that example driver in this commit: https://github.com/nathanleclaire/docker-machine-xhyve/commit/dfb0d8bbbc43beca22f8136c43b68c0610889a13

Some of it as well is just revisions to the driver such as fixing an issue with VBox version checking, updating it to use `BaseDriver`, etc.

**Comment by nathanleclaire** [comment]
I've discovered an issue with leaking goroutines / processes after the main process exits, so that will need to be debugged before this is ready for prime time as well.

**Comment by zchee** [comment]
@nathanleclaire Yes!
This PR is it works until the `error: open /var/db/dhcpd_leases` error :)

I start with the debug, and the refactoring...

> I've discovered an issue with leaking goroutines / processes after the main process exits, so that will need to be debugged before this is ready for prime time as well

This problem caused by `libmachine` issue?
If true, the time being I do not touch.

I will wait @nathanleclaire reply.
Thanks.

**Comment by nlamirault** [comment]
hi
@nathanleclaire any doc to help us to understand how compile it ? 
Thanks !

**Comment by nathanleclaire** [comment]
Should note that this also includes https://github.com/docker/machine/pull/1685: I needed it to make a `dind` plugin I've been prototyping work correctly.

**Comment by zchee** [comment]
@nlamirault 
For example for usage `libmachine-rpc`, [docker-machine-hypercore](https://github.com/zchee/docker-machine-hypercore).
This repo is not works now, but How to install It is written in README.md.

Check it out.

**Comment by nlamirault** [comment]
@zchee thanks

**Comment by janeczku** [comment]
@zchee any particular reason why you are building the driver binary with `GOGC=off`?

**Comment by zchee** [comment]
@janeczku Hi,

`GOGC=off` is not that I specified. It @nathanleclaire was specified in the Makefile.
See https://github.com/nathanleclaire/docker-machine-xhyve/blob/master/bin/Makefile.
I do not even know why, but there is something meaning.

**Comment by nathanleclaire** [comment]
`GOGC=off` was set due to having heard that it helps speed up compiles, but I admit I have no provable basis for the claim, so it's not particularly necessary.

**Comment by nathanleclaire** [comment]
Please move discussion to: https://github.com/docker/machine/pull/1902

**Pull request closed without merging**
